remote_theme: CaptainIRS/hacker-plus-theme

title: ruycr4ft
author: ruycr4ft
description: Writeups and Security research
disqus_forum_shortname:
google_site_verification_content: # The 'content' tag for site verification
google_analytics: # Your Google Analytics Tracking ID

# Usernames and badges
htb_badge_no: 1253217
thm_badge_no: # Go to https://tryhackme.com/profile -> Public Profile -> Get Badge ID
show_thm_htb_badges_in_nav: true
github_username: ruycr4ft
gitlab: 
medium:
stackoverflow: users/24158262/ruycr4ft
hacker_news:
linkedin: 
twitch:
youtube: 
twitter: ruycr4ft
facebook:
instagram:
reddit:
pinterest:
telegram:
steam:

# -------DO NOT ALTER -------#
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true